version: '3.3'

services:
   db:
     image: <IMAGE MYSQL 5.7>
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: tutoETS
       MYSQL_DATABASE: tutoriel
       MYSQL_USER: <USERNAME>
       MYSQL_PASSWORD: <PASSWORD>

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - <PORT LOCAL: PORT WORDPRESS>
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: <USERNAME>
       WORDPRESS_DB_PASSWORD: <PASSWORD>
       WORDPRESS_DB_NAME: tutoriel
volumes:
    db_data: {}
